import React, { useState } from 'react';
import { 
  Briefcase, 
  Plus, 
  FileText, 
  Printer, 
  CheckCircle2, 
  ShieldAlert, 
  User, 
  Clock, 
  Layers,
  Send,
  Download,
  AlertOctagon,
  ShieldCheck
} from 'lucide-react';
import { playCyberClick, playContainmentSound } from '../utils/audio';

export default function CaseManagement({ cases, onCreateCase }) {
  const [caseList, setCaseList] = useState(cases);
  const [selectedCase, setSelectedCase] = useState(cases[0] || null);
  const [newNote, setNewNote] = useState('');

  // Keep selectedCase synced if cases prop updates
  React.useEffect(() => {
    setCaseList(cases);
    if (!selectedCase && cases.length > 0) {
      setSelectedCase(cases[0]);
    }
  }, [cases]);

  const handleAddNote = (e) => {
    e.preventDefault();
    if (!newNote.trim() || !selectedCase) return;
    playCyberClick();

    const updatedNote = `[${new Date().toLocaleTimeString()} - Lead Analyst]: ${newNote.trim()}`;
    const updated = {
      ...selectedCase,
      notes: [...(selectedCase.notes || []), updatedNote]
    };

    setSelectedCase(updated);
    setCaseList(prev => prev.map(c => c.id === updated.id ? updated : c));
    setNewNote('');
  };

  const handleUpdateStatus = (newStatus) => {
    if (!selectedCase) return;
    playContainmentSound();

    const updated = {
      ...selectedCase,
      status: newStatus
    };

    setSelectedCase(updated);
    setCaseList(prev => prev.map(c => c.id === updated.id ? updated : c));
  };

  const handleExportMarkdown = (caseObj) => {
    if (!caseObj) return;
    playCyberClick();

    const reportContent = `# INCIDENT RESPONSE REPORT — ${caseObj.id}

**Title:** ${caseObj.title}
**Severity:** ${caseObj.severity}
**Status:** ${caseObj.status}
**Assigned Analyst:** ${caseObj.assignedTo}
**Target Asset:** ${caseObj.host}
**MITRE Technique:** ${caseObj.mitreTechnique}
**Generated Date:** ${new Date().toUTCString()}

---

## 1. Executive Summary
Anomalous adversary activity was detected and correlated by the SOC Sentinel Detection Engine.

## 2. Containment Actions Taken
${caseObj.actionsTaken?.length > 0 ? caseObj.actionsTaken.map(a => `- ${a}`).join('\n') : '- Automated Host / Perimeter containment initiated.'}

## 3. Investigation Notes Log
${caseObj.notes?.map(n => `- ${n}`).join('\n') || '- No analyst notes recorded.'}

---
*Report generated by SOC Sentinel Cyber Operations Platform.*
`;

    const dataStr = "data:text/markdown;charset=utf-8," + encodeURIComponent(reportContent);
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `${caseObj.id}_incident_report.md`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="cyber-card p-5 border-l-4 border-l-cyan-500 shadow-glow-cyan/20">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <h2 className="text-lg font-bold text-slate-100 flex items-center space-x-2 font-mono">
              <Briefcase className="w-5 h-5 text-cyan-400" />
              <span>SOC Incident Case Management & Executive Report Exporter</span>
            </h2>
            <p className="text-xs text-slate-400 mt-1">
              Track active investigations, document analyst root-cause forensic notes, update containment statuses, and export formal reports.
            </p>
          </div>
        </div>
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Case List */}
        <div className="lg:col-span-5 cyber-card p-5 space-y-3">
          <div className="flex items-center justify-between pb-3 border-b border-cyber-border text-xs font-mono">
            <h3 className="font-bold uppercase text-slate-400">
              Active Incident Tickets ({caseList.length})
            </h3>
            <span className="text-cyan-400 font-semibold">● TRIAGE QUEUE</span>
          </div>

          <div className="space-y-2.5 max-h-[560px] overflow-y-auto pr-1">
            {caseList.map((c) => {
              const isSelected = selectedCase?.id === c.id;
              const isCritical = c.severity === 'CRITICAL';
              const isHigh = c.severity === 'HIGH';

              return (
                <div
                  key={c.id}
                  onClick={() => { playCyberClick(); setSelectedCase(c); }}
                  className={`p-3.5 rounded-lg border cursor-pointer transition-all ${
                    isSelected
                      ? 'bg-cyan-950/40 border-cyan-500 shadow-glow-cyan/20 ring-1 ring-cyan-500'
                      : 'bg-cyber-bg/70 border-cyber-border hover:border-slate-600'
                  }`}
                >
                  <div className="flex items-center justify-between mb-1.5 font-mono text-xs">
                    <span className="text-cyan-400 font-bold">{c.id}</span>
                    <span className={`cyber-badge text-[10px] ${
                      isCritical ? 'bg-red-500/20 text-red-400 border border-red-500/30' : (isHigh ? 'bg-amber-500/20 text-amber-400 border border-amber-500/30' : 'bg-blue-500/20 text-blue-400 border border-blue-500/30')
                    }`}>
                      {c.severity}
                    </span>
                  </div>

                  <h4 className="text-xs font-bold text-slate-100 line-clamp-1 font-sans">{c.title}</h4>

                  <div className="flex items-center justify-between text-[11px] font-mono text-slate-400 mt-2">
                    <span>Host: <strong className="text-slate-200">{c.host}</strong></span>
                    <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${
                      c.status === 'CLOSED' ? 'bg-emerald-950 text-emerald-400 border border-emerald-500/40' : (c.status === 'CONTAINED' ? 'bg-amber-950 text-amber-300 border border-amber-500/40' : 'bg-red-950 text-red-300 border border-red-500/40')
                    }`}>
                      {c.status}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Case Detail Inspector & Notes Timeline */}
        <div className="lg:col-span-7 cyber-card p-6 flex flex-col justify-between">
          <div>
            <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-4 border-b border-cyber-border gap-3">
              <div>
                <span className="text-[10px] font-mono uppercase text-slate-500">Incident Dossier</span>
                <h3 className="text-lg font-bold font-mono text-cyan-300">
                  {selectedCase ? selectedCase.id : 'No Case Selected'}
                </h3>
              </div>

              {selectedCase && (
                <button
                  onClick={() => handleExportMarkdown(selectedCase)}
                  className="px-3 py-1.5 bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-slate-950 rounded-lg text-xs font-bold font-mono flex items-center space-x-1.5 shadow-glow-cyan transition self-start sm:self-auto"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Download Report (MD)</span>
                </button>
              )}
            </div>

            {selectedCase ? (
              <div className="mt-5 space-y-4 text-xs font-mono">
                <div>
                  <h4 className="text-base font-bold text-slate-100 font-sans">{selectedCase.title}</h4>
                  <div className="flex flex-wrap items-center gap-2 mt-1.5">
                    <span className="text-slate-400">Assigned: <strong className="text-slate-200">{selectedCase.assignedTo}</strong></span>
                    <span className="text-slate-600">•</span>
                    <span className="text-slate-400">Asset: <strong className="text-cyan-400">{selectedCase.host}</strong></span>
                    <span className="text-slate-600">•</span>
                    <span className="text-slate-400">MITRE: <strong className="text-purple-400">{selectedCase.mitreTechnique}</strong></span>
                  </div>
                </div>

                {/* Status Toggles */}
                <div className="p-3 bg-cyber-bg rounded-lg border border-cyber-border">
                  <span className="text-slate-500 uppercase text-[10px] block mb-2">Investigation Status</span>
                  <div className="flex flex-wrap gap-2">
                    {['NEW', 'IN_PROGRESS', 'CONTAINED', 'CLOSED'].map((st) => (
                      <button
                        key={st}
                        onClick={() => handleUpdateStatus(st)}
                        className={`px-3 py-1 rounded text-xs font-bold transition ${
                          selectedCase.status === st
                            ? 'bg-cyan-500/20 text-cyan-300 border border-cyan-500/50 shadow-glow-cyan'
                            : 'bg-cyber-panel text-slate-400 border border-cyber-border hover:border-slate-500'
                        }`}
                      >
                        {st}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Analyst Notes Log */}
                <div>
                  <span className="text-slate-500 uppercase text-[10px] block mb-1.5">Analyst Timeline & Forensic Notes</span>
                  <div className="space-y-2 max-h-48 overflow-y-auto pr-1">
                    {selectedCase.notes?.map((n, i) => (
                      <div key={i} className="p-2.5 bg-[#05080f] rounded border border-cyber-border text-slate-300 font-sans text-xs leading-relaxed">
                        {n}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Add Note Form */}
                <form onSubmit={handleAddNote} className="flex items-center space-x-2 pt-2">
                  <input
                    type="text"
                    placeholder="Add forensic observation or mitigation update..."
                    value={newNote}
                    onChange={(e) => setNewNote(e.target.value)}
                    className="flex-1 bg-cyber-bg border border-cyber-border rounded px-3 py-2 text-xs text-slate-200 font-sans focus:outline-none focus:border-cyan-500"
                  />
                  <button
                    type="submit"
                    className="px-4 py-2 bg-cyan-600 hover:bg-cyan-500 text-slate-950 font-bold rounded text-xs font-mono flex items-center space-x-1 transition"
                  >
                    <Send className="w-3.5 h-3.5" />
                    <span>Post</span>
                  </button>
                </form>
              </div>
            ) : (
              <div className="text-center py-24 text-slate-500 font-mono text-xs">
                Select an incident ticket from the queue to review details and document case notes.
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
