import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Bell, Search, Filter, ShieldAlert, ExternalLink, RefreshCw } from 'lucide-react';
import { api } from '../services/api';
import { Alert } from '../types';

export const AlertsPage: React.FC = () => {
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [severityFilter, setSeverityFilter] = useState('ALL');
  const [statusFilter, setStatusFilter] = useState('ALL');

  const loadAlerts = async () => {
    try {
      setLoading(true);
      const data = await api.getAlerts({
        limit: 100,
        severity: severityFilter === 'ALL' ? undefined : severityFilter,
        status_filter: statusFilter === 'ALL' ? undefined : statusFilter,
        search: search || undefined
      });
      setAlerts(data);
    } catch (err) {
      console.error('Failed to fetch alerts:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, [severityFilter, statusFilter, search]);

  const getSeverityBadge = (sev: string) => {
    switch (sev.toUpperCase()) {
      case 'CRITICAL': return 'bg-red-500/10 text-red-400 border-red-500/30';
      case 'HIGH': return 'bg-orange-500/10 text-orange-400 border-orange-500/30';
      case 'MEDIUM': return 'bg-yellow-500/10 text-yellow-400 border-yellow-500/30';
      default: return 'bg-blue-500/10 text-blue-400 border-blue-500/30';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-white font-mono">SOC SECURITY ALERTS FEED</h1>
          <p className="text-xs text-gray-400 font-mono">Real-time threat alerts generated by Detection Engine rules</p>
        </div>
        <button
          onClick={loadAlerts}
          className="flex items-center space-x-2 px-3 py-1.5 bg-[#1F2937] hover:bg-gray-700 text-gray-300 text-xs font-mono rounded-lg border border-gray-700 transition-colors"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
          <span>REFRESH ALERTS</span>
        </button>
      </div>

      {/* Filter Toolbar */}
      <div className="bg-[#111827] border border-gray-800 rounded-xl p-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="relative flex-1 max-w-md">
          <Search className="w-4 h-4 text-gray-500 absolute left-3 top-2.5" />
          <input
            type="text"
            placeholder="Search by Title, Rule, IP, User, Alert ID..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-full bg-[#1F2937] border border-gray-700 rounded-lg pl-9 pr-3 py-2 text-xs text-gray-200 placeholder-gray-500 focus:outline-none focus:border-blue-500 font-mono"
          />
        </div>

        <div className="flex flex-wrap items-center gap-3">
          {/* Severity Dropdown */}
          <div className="flex items-center space-x-2">
            <span className="text-xs text-gray-400 font-mono">SEVERITY:</span>
            <select
              value={severityFilter}
              onChange={(e) => setSeverityFilter(e.target.value)}
              className="bg-[#1F2937] border border-gray-700 text-xs text-gray-200 rounded-lg px-2.5 py-1.5 font-mono focus:outline-none"
            >
              <option value="ALL">All Severities</option>
              <option value="CRITICAL">Critical</option>
              <option value="HIGH">High</option>
              <option value="MEDIUM">Medium</option>
              <option value="LOW">Low</option>
            </select>
          </div>

          {/* Status Dropdown */}
          <div className="flex items-center space-x-2">
            <span className="text-xs text-gray-400 font-mono">STATUS:</span>
            <select
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
              className="bg-[#1F2937] border border-gray-700 text-xs text-gray-200 rounded-lg px-2.5 py-1.5 font-mono focus:outline-none"
            >
              <option value="ALL">All Statuses</option>
              <option value="New">New</option>
              <option value="Investigating">Investigating</option>
              <option value="Resolved">Resolved</option>
              <option value="False Positive">False Positive</option>
            </select>
          </div>
        </div>
      </div>

      {/* Alerts Table */}
      <div className="bg-[#111827] border border-gray-800 rounded-xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead className="bg-[#1F2937] text-gray-400 uppercase">
              <tr>
                <th className="px-4 py-3">SEVERITY</th>
                <th className="px-4 py-3">ALERT ID</th>
                <th className="px-4 py-3">TITLE / RULE</th>
                <th className="px-4 py-3">SOURCE IP</th>
                <th className="px-4 py-3">TARGET USER</th>
                <th className="px-4 py-3">RISK SCORE</th>
                <th className="px-4 py-3">MITRE ATT&CK</th>
                <th className="px-4 py-3">STATUS</th>
                <th className="px-4 py-3 text-right">ACTION</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-800">
              {alerts.length === 0 ? (
                <tr>
                  <td colSpan={9} className="py-12 text-center text-gray-500">
                    No matching security alerts found.
                  </td>
                </tr>
              ) : (
                alerts.map((alert) => (
                  <tr key={alert.id} className="hover:bg-gray-800/40 transition-colors">
                    <td className="px-4 py-3.5">
                      <span className={`px-2 py-0.5 rounded text-[10px] border font-bold ${getSeverityBadge(alert.severity)}`}>
                        {alert.severity}
                      </span>
                    </td>
                    <td className="px-4 py-3.5 font-bold text-blue-400">{alert.alert_id}</td>
                    <td className="px-4 py-3.5 max-w-xs">
                      <div className="font-semibold text-gray-100 truncate">{alert.title}</div>
                      <div className="text-[10px] text-gray-400 truncate">{alert.rule_name}</div>
                    </td>
                    <td className="px-4 py-3.5 text-gray-300 font-bold">{alert.source_ip || 'N/A'}</td>
                    <td className="px-4 py-3.5 text-gray-400">{alert.username || 'System'}</td>
                    <td className="px-4 py-3.5 font-bold">
                      <span className={`px-2 py-0.5 rounded text-[10px] ${
                        alert.risk_score >= 80 ? 'bg-red-500/20 text-red-400' :
                        alert.risk_score >= 60 ? 'bg-orange-500/20 text-orange-400' : 'bg-yellow-500/20 text-yellow-400'
                      }`}>
                        {alert.risk_score} / 100
                      </span>
                    </td>
                    <td className="px-4 py-3.5">
                      <span className="bg-gray-800 text-gray-300 px-2 py-0.5 rounded text-[10px] border border-gray-700">
                        {alert.mitre_technique || 'T1110'}
                      </span>
                    </td>
                    <td className="px-4 py-3.5">
                      <span className={`px-2 py-0.5 rounded text-[10px] ${
                        alert.status === 'New' ? 'bg-blue-500/10 text-blue-400 border border-blue-500/30' :
                        alert.status === 'Investigating' ? 'bg-yellow-500/10 text-yellow-400 border border-yellow-500/30' :
                        'bg-emerald-500/10 text-emerald-400 border border-emerald-500/30'
                      }`}>
                        {alert.status}
                      </span>
                    </td>
                    <td className="px-4 py-3.5 text-right">
                      <Link
                        to={`/alerts/${alert.alert_id}`}
                        className="inline-flex items-center space-x-1 text-blue-400 hover:text-blue-300 font-bold bg-blue-500/10 border border-blue-500/20 px-2.5 py-1 rounded transition-colors"
                      >
                        <span>Investigate</span>
                        <ExternalLink className="w-3 h-3" />
                      </Link>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
